# Generated by Django 3.1.1 on 2020-11-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.teacher')),
            ],
            options={
                'unique_together': {('course', 'class_id', 'teacher')},
            },
        ),
    ]
